# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 08:21
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='bot enabled')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.IntegerField(unique=True, verbose_name='Twitch user ID')),
                ('logo', models.URLField(default='', verbose_name='Twitch logo URL')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='botoptions',
            name='twitch_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_options', to='streams.TwitchUser', verbose_name='bot options'),
        ),
        migrations.AddField(
            model_name='botoptions',
            name='beatmap_allowed_status',
            field=models.CharField(default='1,2', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^([-\\d,])+$', 32), 'Enter only integers separated by commas.', 'invalid')], verbose_name='allowed beatmap status for requests'),
        ),
        migrations.AddField(
            model_name='botoptions',
            name='beatmap_max_stars',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='maximum allowed stars for beatmap requests'),
        ),
        migrations.AddField(
            model_name='botoptions',
            name='beatmap_min_stars',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='minimum allowed stars for beatmap requests'),
        ),
        migrations.AddField(
            model_name='botoptions',
            name='subs_only',
            field=models.BooleanField(default=False, verbose_name='subscriber only mode'),
        ),
    ]
