# Generated by Django 3.2.13 on 2022-04-28 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botoptions',
            name='beatmap_max_stars',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='maximum allowed stars for beatmap requests'),
        ),
        migrations.AlterField(
            model_name='botoptions',
            name='beatmap_min_stars',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='minimum allowed stars for beatmap requests'),
        ),
        migrations.AlterField(
            model_name='botoptions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twitchuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
