version: "3.8"

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_13_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    restart: always
    networks:
      - default

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    restart: always
    expose:
      - "5000"
    volumes:
      - postgres_backup:/backups
    networks:
      - default
      - nginx-proxy

  irc:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - django
    command: python /app/manage.py ircbot
    env_file: .env
    restart: always
    networks:
      - default
      - nginx-proxy

  redis:
    image: redis:7.0
    restart: always
    networks:
      - default
      - nginx-proxy

volumes:
  postgres_13_data:
  postgres_backup:

networks:
  default:
  nginx-proxy:
    name: nginx-proxy
    external: true
